[[GANAK]]
arch = "aarch64"
git-tree-sha1 = "69e363ed1644af4f9498e8b2392038b1cf8af4a8"
os = "macos"

    [[GANAK.download]]
    sha256 = "d5551eb650f5ac59587616c92731b7ffd1102828ed6d797df52f1884af1a35b1"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.aarch64-apple-darwin.tar.gz"
[[GANAK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "8bec5a6f6b4ceaaec26a8234cb47f2763064b548"
libc = "glibc"
os = "linux"

    [[GANAK.download]]
    sha256 = "70bb256184a389f5998198ced2866e90386b704448fde19fa1f8d72e2eed3b89"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.aarch64-linux-gnu-cxx11.tar.gz"
[[GANAK]]
arch = "aarch64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "87c36a2ad27b58391ed106f0c6e912a51c331556"
libc = "musl"
os = "linux"

    [[GANAK.download]]
    sha256 = "dbabfc0c7fd804938b866eddba6ab0a849bed0bf9ae3309e2d7ae48293b598c4"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.aarch64-linux-musl-cxx11.tar.gz"
[[GANAK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "7dac34229e028e580140f37f40bfce8b72a6bc3c"
libc = "glibc"
os = "linux"

    [[GANAK.download]]
    sha256 = "4eb15f603dd7531eaa8badc12571402e79e16a3471eb4a82515d065878fdc16f"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.armv6l-linux-gnueabihf-cxx11.tar.gz"
[[GANAK]]
arch = "armv6l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "421b5e3d01af89c62be3a589dc26d6c93fc89155"
libc = "musl"
os = "linux"

    [[GANAK.download]]
    sha256 = "9ca51b9006219a868430c9d0bf12596e819b903220aa9a0f3b5f8d3d4a117c6c"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.armv6l-linux-musleabihf-cxx11.tar.gz"
[[GANAK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1da0bdc5350c1c338e99f4eef2e2c98e450a2dfd"
libc = "glibc"
os = "linux"

    [[GANAK.download]]
    sha256 = "8142f39c7aee6f7e2de7fd6b028743a5c90aeb050cae15a5ed2d4b296b79c6c6"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.armv7l-linux-gnueabihf-cxx11.tar.gz"
[[GANAK]]
arch = "armv7l"
call_abi = "eabihf"
cxxstring_abi = "cxx11"
git-tree-sha1 = "78742b0aa315ca070f1b399162d026eb921b94d7"
libc = "musl"
os = "linux"

    [[GANAK.download]]
    sha256 = "94610a1ad0663c8c99df0dcd172b0f69382993ac20295dff292b630b3c55c3b7"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.armv7l-linux-musleabihf-cxx11.tar.gz"
[[GANAK]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cced82d325feeabad5dcac938a2c1afe6affd0fa"
libc = "glibc"
os = "linux"

    [[GANAK.download]]
    sha256 = "45c7748c3f2ccd1c86c7d2ea95a65567b0def65cd05ec5e2fe6f34b855b5b8f9"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.i686-linux-gnu-cxx11.tar.gz"
[[GANAK]]
arch = "i686"
cxxstring_abi = "cxx11"
git-tree-sha1 = "68bba7e7461d18c0a21ecdd252d0aefdf2a8b88e"
libc = "musl"
os = "linux"

    [[GANAK.download]]
    sha256 = "ec14db05734ac3959f6b4e996ffe4ac5e97a52767c2972d81fee4edaf2930b73"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.i686-linux-musl-cxx11.tar.gz"
[[GANAK]]
arch = "powerpc64le"
cxxstring_abi = "cxx11"
git-tree-sha1 = "1d706f667c0bc556b0d8e047d1de39e72a5485d7"
libc = "glibc"
os = "linux"

    [[GANAK.download]]
    sha256 = "fb663003a707d3fefdad62ed030869891f6c8accf311201879c993b7475ff86d"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.powerpc64le-linux-gnu-cxx11.tar.gz"
[[GANAK]]
arch = "riscv64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "2e33b4bd7f638ccfc66fd89eb79fff980bafa4e9"
libc = "glibc"
os = "linux"

    [[GANAK.download]]
    sha256 = "52851358367aa3463d1ff36ab7791cfd4e90982cb0f8a48bf5572f261b25ba36"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.riscv64-linux-gnu-cxx11.tar.gz"
[[GANAK]]
arch = "x86_64"
git-tree-sha1 = "e39a7609036072eb2ef3b562a24770e566875817"
os = "macos"

    [[GANAK.download]]
    sha256 = "f92bd7990a8da13e79bb83d202b5a43b6de4123787e9810f364d9e406c9d804e"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.x86_64-apple-darwin.tar.gz"
[[GANAK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "9fa3627c2961a0452668160a4b55b5330a2986eb"
libc = "glibc"
os = "linux"

    [[GANAK.download]]
    sha256 = "9c94224ddbf8670c408f0aa987109d8a87a9116e4587ac3013ef674baf01a22d"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.x86_64-linux-gnu-cxx11.tar.gz"
[[GANAK]]
arch = "x86_64"
cxxstring_abi = "cxx11"
git-tree-sha1 = "cfbee096283490c0e17d6e9d54e1be70bd981b83"
libc = "musl"
os = "linux"

    [[GANAK.download]]
    sha256 = "b31754f788c8e36d10588f1993b85251a1821a386563bfc0919542d9ddc93bd1"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.x86_64-linux-musl-cxx11.tar.gz"
[[GANAK]]
arch = "x86_64"
git-tree-sha1 = "534b8e2293eb3d61b30122b67e20bf2f045ed516"
os = "freebsd"

    [[GANAK.download]]
    sha256 = "b4bf7ac12d7c4051ca12fc2d1d55926d572a52573b6875d6a30931fc190e44be"
    url = "https://github.com/JuliaBinaryWrappers/GANAK_jll.jl/releases/download/GANAK-v2.5.2+0/GANAK.v2.5.2.x86_64-unknown-freebsd.tar.gz"
